package orm

import (
	"cmp"
	"context"
	"errors"
	"fmt"
	"reflect"
	"slices"
	"sync"
	"time"
)

var (
	// ErrNotFound is returned when no row matches (firstOrFail, findOrFail).
	ErrNotFound = errors.New("orm: record not found")
	// ErrMultipleRecords is returned by Sole when more than one row matches.
	ErrMultipleRecords = errors.New("orm: multiple records found")
)

// KeyType is how a table's primary key is generated.
type KeyType int

const (
	KeyAutoIncrement KeyType = iota // database-assigned integer
	KeyUUID                         // UUIDv7 generated on create (HasUuids)
	KeyULID                         // ULID generated on create (HasUlids)
	KeyManual                       // caller sets it
)

// Table describes how model M maps to a table. Generated by ormgen from the
// //orm:table directive — the equivalent of Laravel 13's #[Table],
// #[Connection], #[WithoutTimestamps] and SoftDeletes configuration.
type Table[M any] struct {
	Name       string
	Connection string // empty: DefaultConnection
	PrimaryKey string // empty: no primary key (e.g. pivot tables)
	KeyType    KeyType
	CreatedAt  string // empty: not maintained
	UpdatedAt  string
	DeletedAt  string // non-empty enables soft deletes
	MorphAlias string // value stored in *_type columns; defaults to Name
	Columns    []string
	// NullZero lists columns whose zero value is written as NULL
	// (db:"country_id,nullzero"), e.g. optional foreign keys.
	NullZero []string

	// Ptr returns a pointer to the field backing column (persisted or virtual).
	Ptr func(m *M, column string) any
	// State returns the embedded orm.Model.
	State func(m *M) *Model

	mu        sync.RWMutex
	scopes    []namedScope[M]
	listeners map[Event][]func(context.Context, *M) error
}

// Model is embedded in every model struct. It tracks whether the row
// exists and what it looked like when loaded, for dirty checking.
type Model struct {
	exists          bool
	recentlyCreated bool
	original        map[string]any
	changes         []string
}

// Exists reports whether the model was loaded from or saved to the database.
func (m *Model) Exists() bool { return m.exists }

// WasRecentlyCreated reports whether the last save inserted the row.
func (m *Model) WasRecentlyCreated() bool { return m.recentlyCreated }

func (t *Table[M]) state(m *M) *Model { return t.State(m) }

func (t *Table[M]) connection() string { return cmp.Or(t.Connection, DefaultConnection) }

func (t *Table[M]) morphAlias() string { return cmp.Or(t.MorphAlias, t.Name) }

func (t *Table[M]) softDeletes() bool { return t.DeletedAt != "" }

// value reads a column's current value from m.
func (t *Table[M]) value(m *M, col string) any {
	return reflect.ValueOf(t.Ptr(m, col)).Elem().Interface()
}

func (t *Table[M]) setValue(m *M, col string, v any) {
	dst := reflect.ValueOf(t.Ptr(m, col)).Elem()
	src := reflect.ValueOf(v)
	switch {
	case dst.Kind() == reflect.Pointer && src.Type() == dst.Type().Elem():
		p := reflect.New(src.Type())
		p.Elem().Set(src)
		dst.Set(p)
	case src.Type().ConvertibleTo(dst.Type()):
		dst.Set(src.Convert(dst.Type()))
	default:
		panic(fmt.Sprintf("orm: cannot assign %T to %s.%s (%s)", v, t.Name, col, dst.Type()))
	}
}

// dbValue is the value written for col: nil for zero nullzero columns
// and for zero times (which no database stores meaningfully).
func (t *Table[M]) dbValue(m *M, col string) any { return t.writeValue(col, t.value(m, col)) }

func (t *Table[M]) writeValue(col string, v any) any {
	if tm, ok := v.(time.Time); ok && tm.IsZero() {
		return nil
	}
	if slices.Contains(t.NullZero, col) && isZero(v) {
		return nil
	}
	return v
}

// key returns the primary key value of m.
func (t *Table[M]) key(m *M) any { return t.value(m, t.PrimaryKey) }

// sync marks m as persisted and snapshots its columns as the new original.
func (t *Table[M]) sync(m *M) {
	st := t.state(m)
	st.exists = true
	st.original = make(map[string]any, len(t.Columns))
	for _, c := range t.Columns {
		st.original[c] = t.value(m, c)
	}
}

// Dirty returns the columns changed since m was loaded or saved (getDirty).
func (t *Table[M]) Dirty(m *M) []string {
	st := t.state(m)
	var dirty []string
	for _, c := range t.Columns {
		if orig, ok := st.original[c]; !ok || !equal(orig, t.value(m, c)) {
			dirty = append(dirty, c)
		}
	}
	return dirty
}

// IsDirty reports whether any column (or any of cols) changed.
func (t *Table[M]) IsDirty(m *M, cols ...AnyColumn[M]) bool {
	dirty := t.Dirty(m)
	if len(cols) == 0 {
		return len(dirty) > 0
	}
	return slices.ContainsFunc(cols, func(c AnyColumn[M]) bool { return slices.Contains(dirty, c.Name()) })
}

// IsClean is the inverse of IsDirty.
func (t *Table[M]) IsClean(m *M, cols ...AnyColumn[M]) bool { return !t.IsDirty(m, cols...) }

// WasChanged reports whether the last save changed any column (or any of cols).
func (t *Table[M]) WasChanged(m *M, cols ...AnyColumn[M]) bool {
	changes := t.state(m).changes
	if len(cols) == 0 {
		return len(changes) > 0
	}
	return slices.ContainsFunc(cols, func(c AnyColumn[M]) bool { return slices.Contains(changes, c.Name()) })
}

// IsNot is the inverse of Is.
func (t *Table[M]) IsNot(a, b *M) bool { return !t.Is(a, b) }

// Is reports whether a and b are the same row (same table, connection and key).
func (t *Table[M]) Is(a, b *M) bool {
	return t.PrimaryKey != "" && equal(t.key(a), t.key(b))
}

// ---------------------------------------------------------------------------
// Global scopes
// ---------------------------------------------------------------------------

type namedScope[M any] struct {
	name string
	fn   func(Query[M]) Query[M]
}

// softDeleteScope is the name of the built-in soft delete global scope.
const softDeleteScope = "softDeletes"

// AddGlobalScope registers a scope applied to every query on the table
// (including relation and whereHas subqueries) unless removed with
// WithoutGlobalScope.
func (t *Table[M]) AddGlobalScope(name string, fn func(Query[M]) Query[M]) {
	t.mu.Lock()
	defer t.mu.Unlock()
	t.scopes = append(t.scopes, namedScope[M]{name, fn})
}

func (t *Table[M]) globalScopes() []namedScope[M] {
	t.mu.RLock()
	defer t.mu.RUnlock()
	return slices.Clone(t.scopes)
}

// ---------------------------------------------------------------------------
// Events and observers
// ---------------------------------------------------------------------------

// Event is a model lifecycle event.
type Event int

const (
	Retrieved Event = iota
	Creating
	Created
	Updating
	Updated
	Saving
	Saved
	Deleting
	Deleted
	Trashed
	ForceDeleting
	ForceDeleted
	Restoring
	Restored
	Replicating
)

// On registers a listener. Returning an error from a "-ing" listener aborts
// the operation (Eloquent's "return false").
func (t *Table[M]) On(e Event, fn func(ctx context.Context, m *M) error) {
	t.mu.Lock()
	defer t.mu.Unlock()
	if t.listeners == nil {
		t.listeners = map[Event][]func(context.Context, *M) error{}
	}
	t.listeners[e] = append(t.listeners[e], fn)
}

// Observe registers every lifecycle method obs implements, e.g.
//
//	func (UserObserver) Creating(ctx context.Context, u *User) error
func (t *Table[M]) Observe(obs any) {
	type h = func(context.Context, *M) error
	methods := map[Event]h{}
	if o, ok := obs.(interface {
		Retrieved(context.Context, *M) error
	}); ok {
		methods[Retrieved] = o.Retrieved
	}
	if o, ok := obs.(interface {
		Creating(context.Context, *M) error
	}); ok {
		methods[Creating] = o.Creating
	}
	if o, ok := obs.(interface {
		Created(context.Context, *M) error
	}); ok {
		methods[Created] = o.Created
	}
	if o, ok := obs.(interface {
		Updating(context.Context, *M) error
	}); ok {
		methods[Updating] = o.Updating
	}
	if o, ok := obs.(interface {
		Updated(context.Context, *M) error
	}); ok {
		methods[Updated] = o.Updated
	}
	if o, ok := obs.(interface {
		Saving(context.Context, *M) error
	}); ok {
		methods[Saving] = o.Saving
	}
	if o, ok := obs.(interface {
		Saved(context.Context, *M) error
	}); ok {
		methods[Saved] = o.Saved
	}
	if o, ok := obs.(interface {
		Deleting(context.Context, *M) error
	}); ok {
		methods[Deleting] = o.Deleting
	}
	if o, ok := obs.(interface {
		Deleted(context.Context, *M) error
	}); ok {
		methods[Deleted] = o.Deleted
	}
	if o, ok := obs.(interface {
		Trashed(context.Context, *M) error
	}); ok {
		methods[Trashed] = o.Trashed
	}
	if o, ok := obs.(interface {
		ForceDeleting(context.Context, *M) error
	}); ok {
		methods[ForceDeleting] = o.ForceDeleting
	}
	if o, ok := obs.(interface {
		ForceDeleted(context.Context, *M) error
	}); ok {
		methods[ForceDeleted] = o.ForceDeleted
	}
	if o, ok := obs.(interface {
		Restoring(context.Context, *M) error
	}); ok {
		methods[Restoring] = o.Restoring
	}
	if o, ok := obs.(interface {
		Restored(context.Context, *M) error
	}); ok {
		methods[Restored] = o.Restored
	}
	if o, ok := obs.(interface {
		Replicating(context.Context, *M) error
	}); ok {
		methods[Replicating] = o.Replicating
	}
	if len(methods) == 0 {
		panic(fmt.Sprintf("orm: %T implements no observer methods for %s", obs, t.Name))
	}
	for e, fn := range methods {
		t.On(e, fn)
	}
}

type quietKey struct{}

// WithoutEvents returns a ctx in which no model events fire
// (saveQuietly, Model::withoutEvents).
func WithoutEvents(ctx context.Context) context.Context {
	return context.WithValue(ctx, quietKey{}, true)
}

func (t *Table[M]) fire(ctx context.Context, e Event, m *M) error {
	if ctx.Value(quietKey{}) != nil {
		return nil
	}
	t.mu.RLock()
	ls := t.listeners[e]
	t.mu.RUnlock()
	for _, fn := range ls {
		if err := fn(ctx, m); err != nil {
			return err
		}
	}
	return nil
}
