// Code generated by ormgen. DO NOT EDIT.

package models

import (
	"github.com/stubbedev/eloquent-go/orm"
	"time"
)

var auditLogTable = &orm.Table[AuditEntry]{
	Name:       "audit_log",
	Connection: "audit",
	PrimaryKey: "id",
	KeyType:    orm.KeyUUID,
	Columns:    []string{"id", "action"},
	Ptr: func(m *AuditEntry, column string) any {
		switch column {
		case "id":
			return &m.ID
		case "action":
			return &m.Action
		}
		return nil
	},
	State: func(m *AuditEntry) *orm.Model { return &m.Model },
}

// AuditLogSchema describes the audit_log table for AuditEntry.
type AuditLogSchema struct {
	*orm.Table[AuditEntry]
	ID     orm.Column[AuditEntry, string]
	Action orm.Column[AuditEntry, string]
}

// AuditLog is the entry point for audit_log: AuditLog.Query(), AuditLog.Find(ctx, id), ...
var AuditLog = AuditLogSchema{
	Table:  auditLogTable,
	ID:     orm.NewColumn(auditLogTable, "id", func(m *AuditEntry) *string { return &m.ID }),
	Action: orm.NewColumn(auditLogTable, "action", func(m *AuditEntry) *string { return &m.Action }),
}

var commentsTable = &orm.Table[Comment]{
	Name:       "comments",
	PrimaryKey: "id",
	KeyType:    orm.KeyAutoIncrement,
	CreatedAt:  "created_at",
	UpdatedAt:  "updated_at",
	Columns:    []string{"id", "commentable_id", "commentable_type", "body", "created_at", "updated_at"},
	Ptr: func(m *Comment, column string) any {
		switch column {
		case "id":
			return &m.ID
		case "commentable_id":
			return &m.CommentableID
		case "commentable_type":
			return &m.CommentableType
		case "body":
			return &m.Body
		case "created_at":
			return &m.CreatedAt
		case "updated_at":
			return &m.UpdatedAt
		}
		return nil
	},
	State: func(m *Comment) *orm.Model { return &m.Model },
}

// CommentsSchema describes the comments table for Comment.
type CommentsSchema struct {
	*orm.Table[Comment]
	ID              orm.Column[Comment, int64]
	CommentableID   orm.Column[Comment, int64]
	CommentableType orm.Column[Comment, string]
	Body            orm.Column[Comment, string]
	CreatedAt       orm.Column[Comment, time.Time]
	UpdatedAt       orm.Column[Comment, time.Time]
}

// Comments is the entry point for comments: Comments.Query(), Comments.Find(ctx, id), ...
var Comments = CommentsSchema{
	Table:           commentsTable,
	ID:              orm.NewColumn(commentsTable, "id", func(m *Comment) *int64 { return &m.ID }),
	CommentableID:   orm.NewColumn(commentsTable, "commentable_id", func(m *Comment) *int64 { return &m.CommentableID }),
	CommentableType: orm.NewColumn(commentsTable, "commentable_type", func(m *Comment) *string { return &m.CommentableType }),
	Body:            orm.NewColumn(commentsTable, "body", func(m *Comment) *string { return &m.Body }),
	CreatedAt:       orm.NewColumn(commentsTable, "created_at", func(m *Comment) *time.Time { return &m.CreatedAt }),
	UpdatedAt:       orm.NewColumn(commentsTable, "updated_at", func(m *Comment) *time.Time { return &m.UpdatedAt }),
}

var countriesTable = &orm.Table[Country]{
	Name:       "countries",
	PrimaryKey: "id",
	KeyType:    orm.KeyAutoIncrement,
	Columns:    []string{"id", "name"},
	Ptr: func(m *Country, column string) any {
		switch column {
		case "id":
			return &m.ID
		case "name":
			return &m.Name
		}
		return nil
	},
	State: func(m *Country) *orm.Model { return &m.Model },
}

// CountriesSchema describes the countries table for Country.
type CountriesSchema struct {
	*orm.Table[Country]
	ID   orm.Column[Country, int64]
	Name orm.Column[Country, string]
}

// Countries is the entry point for countries: Countries.Query(), Countries.Find(ctx, id), ...
var Countries = CountriesSchema{
	Table: countriesTable,
	ID:    orm.NewColumn(countriesTable, "id", func(m *Country) *int64 { return &m.ID }),
	Name:  orm.NewColumn(countriesTable, "name", func(m *Country) *string { return &m.Name }),
}

var imagesTable = &orm.Table[Image]{
	Name:       "images",
	PrimaryKey: "id",
	KeyType:    orm.KeyAutoIncrement,
	Columns:    []string{"id", "imageable_id", "imageable_type", "url"},
	Ptr: func(m *Image, column string) any {
		switch column {
		case "id":
			return &m.ID
		case "imageable_id":
			return &m.ImageableID
		case "imageable_type":
			return &m.ImageableType
		case "url":
			return &m.URL
		}
		return nil
	},
	State: func(m *Image) *orm.Model { return &m.Model },
}

// ImagesSchema describes the images table for Image.
type ImagesSchema struct {
	*orm.Table[Image]
	ID            orm.Column[Image, int64]
	ImageableID   orm.Column[Image, int64]
	ImageableType orm.Column[Image, string]
	URL           orm.Column[Image, string]
}

// Images is the entry point for images: Images.Query(), Images.Find(ctx, id), ...
var Images = ImagesSchema{
	Table:         imagesTable,
	ID:            orm.NewColumn(imagesTable, "id", func(m *Image) *int64 { return &m.ID }),
	ImageableID:   orm.NewColumn(imagesTable, "imageable_id", func(m *Image) *int64 { return &m.ImageableID }),
	ImageableType: orm.NewColumn(imagesTable, "imageable_type", func(m *Image) *string { return &m.ImageableType }),
	URL:           orm.NewColumn(imagesTable, "url", func(m *Image) *string { return &m.URL }),
}

var postsTable = &orm.Table[Post]{
	Name:       "posts",
	PrimaryKey: "id",
	KeyType:    orm.KeyAutoIncrement,
	CreatedAt:  "created_at",
	UpdatedAt:  "updated_at",
	Columns:    []string{"id", "user_id", "title", "published", "views", "created_at", "updated_at"},
	Ptr: func(m *Post, column string) any {
		switch column {
		case "id":
			return &m.ID
		case "user_id":
			return &m.UserID
		case "title":
			return &m.Title
		case "published":
			return &m.Published
		case "views":
			return &m.Views
		case "created_at":
			return &m.CreatedAt
		case "updated_at":
			return &m.UpdatedAt
		}
		return nil
	},
	State: func(m *Post) *orm.Model { return &m.Model },
}

// PostsSchema describes the posts table for Post.
type PostsSchema struct {
	*orm.Table[Post]
	ID        orm.Column[Post, int64]
	UserID    orm.Column[Post, int64]
	Title     orm.Column[Post, string]
	Published orm.Column[Post, bool]
	Views     orm.Column[Post, int64]
	CreatedAt orm.Column[Post, time.Time]
	UpdatedAt orm.Column[Post, time.Time]
}

// Posts is the entry point for posts: Posts.Query(), Posts.Find(ctx, id), ...
var Posts = PostsSchema{
	Table:     postsTable,
	ID:        orm.NewColumn(postsTable, "id", func(m *Post) *int64 { return &m.ID }),
	UserID:    orm.NewColumn(postsTable, "user_id", func(m *Post) *int64 { return &m.UserID }),
	Title:     orm.NewColumn(postsTable, "title", func(m *Post) *string { return &m.Title }),
	Published: orm.NewColumn(postsTable, "published", func(m *Post) *bool { return &m.Published }),
	Views:     orm.NewColumn(postsTable, "views", func(m *Post) *int64 { return &m.Views }),
	CreatedAt: orm.NewColumn(postsTable, "created_at", func(m *Post) *time.Time { return &m.CreatedAt }),
	UpdatedAt: orm.NewColumn(postsTable, "updated_at", func(m *Post) *time.Time { return &m.UpdatedAt }),
}

var rolesTable = &orm.Table[Role]{
	Name:       "roles",
	PrimaryKey: "id",
	KeyType:    orm.KeyAutoIncrement,
	Columns:    []string{"id", "name"},
	Ptr: func(m *Role, column string) any {
		switch column {
		case "id":
			return &m.ID
		case "name":
			return &m.Name
		}
		return nil
	},
	State: func(m *Role) *orm.Model { return &m.Model },
}

// RolesSchema describes the roles table for Role.
type RolesSchema struct {
	*orm.Table[Role]
	ID   orm.Column[Role, int64]
	Name orm.Column[Role, string]
}

// Roles is the entry point for roles: Roles.Query(), Roles.Find(ctx, id), ...
var Roles = RolesSchema{
	Table: rolesTable,
	ID:    orm.NewColumn(rolesTable, "id", func(m *Role) *int64 { return &m.ID }),
	Name:  orm.NewColumn(rolesTable, "name", func(m *Role) *string { return &m.Name }),
}

var roleUsersTable = &orm.Table[RoleUser]{
	Name:      "role_user",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
	Columns:   []string{"user_id", "role_id", "granted_by", "created_at", "updated_at"},
	Ptr: func(m *RoleUser, column string) any {
		switch column {
		case "user_id":
			return &m.UserID
		case "role_id":
			return &m.RoleID
		case "granted_by":
			return &m.GrantedBy
		case "created_at":
			return &m.CreatedAt
		case "updated_at":
			return &m.UpdatedAt
		}
		return nil
	},
	State: func(m *RoleUser) *orm.Model { return &m.Model },
}

// RoleUsersSchema describes the role_user table for RoleUser.
type RoleUsersSchema struct {
	*orm.Table[RoleUser]
	UserID    orm.Column[RoleUser, int64]
	RoleID    orm.Column[RoleUser, int64]
	GrantedBy orm.Column[RoleUser, string]
	CreatedAt orm.Column[RoleUser, time.Time]
	UpdatedAt orm.Column[RoleUser, time.Time]
}

// RoleUsers is the entry point for role_user: RoleUsers.Query(), RoleUsers.Find(ctx, id), ...
var RoleUsers = RoleUsersSchema{
	Table:     roleUsersTable,
	UserID:    orm.NewColumn(roleUsersTable, "user_id", func(m *RoleUser) *int64 { return &m.UserID }),
	RoleID:    orm.NewColumn(roleUsersTable, "role_id", func(m *RoleUser) *int64 { return &m.RoleID }),
	GrantedBy: orm.NewColumn(roleUsersTable, "granted_by", func(m *RoleUser) *string { return &m.GrantedBy }),
	CreatedAt: orm.NewColumn(roleUsersTable, "created_at", func(m *RoleUser) *time.Time { return &m.CreatedAt }),
	UpdatedAt: orm.NewColumn(roleUsersTable, "updated_at", func(m *RoleUser) *time.Time { return &m.UpdatedAt }),
}

var tagsTable = &orm.Table[Tag]{
	Name:       "tags",
	PrimaryKey: "id",
	KeyType:    orm.KeyAutoIncrement,
	Columns:    []string{"id", "name"},
	Ptr: func(m *Tag, column string) any {
		switch column {
		case "id":
			return &m.ID
		case "name":
			return &m.Name
		}
		return nil
	},
	State: func(m *Tag) *orm.Model { return &m.Model },
}

// TagsSchema describes the tags table for Tag.
type TagsSchema struct {
	*orm.Table[Tag]
	ID   orm.Column[Tag, int64]
	Name orm.Column[Tag, string]
}

// Tags is the entry point for tags: Tags.Query(), Tags.Find(ctx, id), ...
var Tags = TagsSchema{
	Table: tagsTable,
	ID:    orm.NewColumn(tagsTable, "id", func(m *Tag) *int64 { return &m.ID }),
	Name:  orm.NewColumn(tagsTable, "name", func(m *Tag) *string { return &m.Name }),
}

var taggablesTable = &orm.Table[Taggable]{
	Name:    "taggables",
	Columns: []string{"tag_id", "taggable_id", "taggable_type"},
	Ptr: func(m *Taggable, column string) any {
		switch column {
		case "tag_id":
			return &m.TagID
		case "taggable_id":
			return &m.TaggableID
		case "taggable_type":
			return &m.TaggableType
		}
		return nil
	},
	State: func(m *Taggable) *orm.Model { return &m.Model },
}

// TaggablesSchema describes the taggables table for Taggable.
type TaggablesSchema struct {
	*orm.Table[Taggable]
	TagID        orm.Column[Taggable, int64]
	TaggableID   orm.Column[Taggable, int64]
	TaggableType orm.Column[Taggable, string]
}

// Taggables is the entry point for taggables: Taggables.Query(), Taggables.Find(ctx, id), ...
var Taggables = TaggablesSchema{
	Table:        taggablesTable,
	TagID:        orm.NewColumn(taggablesTable, "tag_id", func(m *Taggable) *int64 { return &m.TagID }),
	TaggableID:   orm.NewColumn(taggablesTable, "taggable_id", func(m *Taggable) *int64 { return &m.TaggableID }),
	TaggableType: orm.NewColumn(taggablesTable, "taggable_type", func(m *Taggable) *string { return &m.TaggableType }),
}

var usersTable = &orm.Table[User]{
	Name:       "users",
	PrimaryKey: "id",
	KeyType:    orm.KeyAutoIncrement,
	CreatedAt:  "created_at",
	UpdatedAt:  "updated_at",
	DeletedAt:  "deleted_at",
	NullZero:   []string{"country_id"},
	Columns:    []string{"id", "country_id", "name", "email", "active", "karma", "settings", "created_at", "updated_at", "deleted_at"},
	Ptr: func(m *User, column string) any {
		switch column {
		case "id":
			return &m.ID
		case "country_id":
			return &m.CountryID
		case "name":
			return &m.Name
		case "email":
			return &m.Email
		case "active":
			return &m.Active
		case "karma":
			return &m.Karma
		case "settings":
			return &m.Settings
		case "created_at":
			return &m.CreatedAt
		case "updated_at":
			return &m.UpdatedAt
		case "deleted_at":
			return &m.DeletedAt
		case "posts_count":
			return &m.PostsCount
		case "post_views":
			return &m.PostViews
		case "has_avatar":
			return &m.HasAvatar
		case "latest_post_title":
			return &m.LatestPostTitle
		}
		return nil
	},
	State: func(m *User) *orm.Model { return &m.Model },
}

// UsersSchema describes the users table for User.
type UsersSchema struct {
	*orm.Table[User]
	ID              orm.Column[User, int64]
	CountryID       orm.Column[User, int64]
	Name            orm.Column[User, string]
	Email           orm.Column[User, string]
	Active          orm.Column[User, bool]
	Karma           orm.Column[User, int]
	Settings        orm.Column[User, orm.JSON[Settings]]
	CreatedAt       orm.Column[User, time.Time]
	UpdatedAt       orm.Column[User, time.Time]
	DeletedAt       orm.Column[User, *time.Time]
	PostsCount      orm.Column[User, int64]
	PostViews       orm.Column[User, int64]
	HasAvatar       orm.Column[User, bool]
	LatestPostTitle orm.Column[User, string]
}

// Users is the entry point for users: Users.Query(), Users.Find(ctx, id), ...
var Users = UsersSchema{
	Table:           usersTable,
	ID:              orm.NewColumn(usersTable, "id", func(m *User) *int64 { return &m.ID }),
	CountryID:       orm.NewColumn(usersTable, "country_id", func(m *User) *int64 { return &m.CountryID }),
	Name:            orm.NewColumn(usersTable, "name", func(m *User) *string { return &m.Name }),
	Email:           orm.NewColumn(usersTable, "email", func(m *User) *string { return &m.Email }),
	Active:          orm.NewColumn(usersTable, "active", func(m *User) *bool { return &m.Active }),
	Karma:           orm.NewColumn(usersTable, "karma", func(m *User) *int { return &m.Karma }),
	Settings:        orm.NewColumn(usersTable, "settings", func(m *User) *orm.JSON[Settings] { return &m.Settings }),
	CreatedAt:       orm.NewColumn(usersTable, "created_at", func(m *User) *time.Time { return &m.CreatedAt }),
	UpdatedAt:       orm.NewColumn(usersTable, "updated_at", func(m *User) *time.Time { return &m.UpdatedAt }),
	DeletedAt:       orm.NewColumn(usersTable, "deleted_at", func(m *User) **time.Time { return &m.DeletedAt }),
	PostsCount:      orm.NewVirtualColumn(usersTable, "posts_count", func(m *User) *int64 { return &m.PostsCount }),
	PostViews:       orm.NewVirtualColumn(usersTable, "post_views", func(m *User) *int64 { return &m.PostViews }),
	HasAvatar:       orm.NewVirtualColumn(usersTable, "has_avatar", func(m *User) *bool { return &m.HasAvatar }),
	LatestPostTitle: orm.NewVirtualColumn(usersTable, "latest_post_title", func(m *User) *string { return &m.LatestPostTitle }),
}

var videosTable = &orm.Table[Video]{
	Name:       "videos",
	PrimaryKey: "id",
	KeyType:    orm.KeyAutoIncrement,
	Columns:    []string{"id", "title"},
	Ptr: func(m *Video, column string) any {
		switch column {
		case "id":
			return &m.ID
		case "title":
			return &m.Title
		}
		return nil
	},
	State: func(m *Video) *orm.Model { return &m.Model },
}

// VideosSchema describes the videos table for Video.
type VideosSchema struct {
	*orm.Table[Video]
	ID    orm.Column[Video, int64]
	Title orm.Column[Video, string]
}

// Videos is the entry point for videos: Videos.Query(), Videos.Find(ctx, id), ...
var Videos = VideosSchema{
	Table: videosTable,
	ID:    orm.NewColumn(videosTable, "id", func(m *Video) *int64 { return &m.ID }),
	Title: orm.NewColumn(videosTable, "title", func(m *Video) *string { return &m.Title }),
}
